# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.FloatField(default='NULL')),
                ('CVV', models.FloatField(default='NULL')),
                ('expiry_month', models.FloatField(default='NULL')),
                ('expiry_year', models.FloatField(default='NULL')),
                ('user_name', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='homepage.customer')),
            ],
        ),
    ]
