# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171106_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_list',
            field=models.CharField(max_length=40),
        ),
    ]
