# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='kaa', max_length=40),
        ),
    ]
